---
title: "Reproducibility Report for \"On the Precipice of a 'Majority-Minority' America: Perceived Status Threat From the Racial Demographic Shift Affects White Americans’ Political Ideology\" by Craig & Richeson (2014, Psychological Science)"
author: "Stacia King (staciak@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Reproducibility reports should all use this template to standardize reporting across projects. These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

Craig & Richeson, 2014, used an online experiment to unpack the link between  racial demographic shifts and the endorsement of conservatism in white American moderates. The study found white moderates leaned more conservative after being primed with racial demographic shifts in favor of current minority groups. In this project I will look to see if findings from Study 3, group status threat mediated the relationship between racial demographic shifts and more conservative ideology, replicates. 

**Clarify key analysis of interest here**  
ANCOVAs with experimental condition as the independent variable and demographic characteristics and baseline political ideology as 
covariates

### Justification for choice of study

As a social psychologist in training, my research interests include intergroup and interpersonal conflict resolution. Particularly I am interested in conflict between groups with unequal power dynamics, such as white people and Black people, or minorities in general. *On the Precipice of a \"Majority-Minority\” America: Perceived Status Threat From the Racial Demographic Shift Affects White Americans’ Political Ideology* by Craig & Richeson (2014, Psychological Science) helps explain the relationship between racial and social progress and white backlash now, and potentially in the future.


### Anticipated challenges

Some anticipated challenges to this replication will be:

* Collecting a similarly gendered sample as the original study, or rather a representative proportion of women moderates.

### Links

Project repository (on Github): [craig2021](https://github.com/psych251/craig2021.git)

Original paper (as hosted in your repo): [view pdf](https://github.com/psych251/craig2014/blob/1af6af3af7d70e11185a62bc317543f77e10cde1/original_paper.pdf)

Open Practice: [original stimuli](https://osf.io/dzv6r/osffiles/PS14_Craig_Richeson_manipulations.pdf/)

## Methods

### Description of the steps required to reproduce the results

1. Gather necessary stimuli from Open Science Framework.

2. Compile stimuli, demographic, independent, and dependent variable items into a Qualtrics survey.

3. Collect data on Prolific from self-identified white political moderates in the United States

4. Run ANCOVAs with the experimental condition as the independent variable and demographic characteristics and baseline political ideology as covariates

### Differences from original study

The demographics of the sample in this replication attempt will likely be different as described in the Anticipated Challenges section above.

The social climate has varied dramatically in numerous waves and directions since the original study was conducted in 2014. It will be interesting to see how and if social attitudes have changed, and in which ways.

## Project Progress Check 1

### Measure of success

The replication will be successful based on whether or not the sample leans more conservative after interacting with the stimuli. Additionally, there will be a full replication if data from the assuaged-threat condition do not lean more conservative after interacting with the stimuli. Differences will be calculated with an ANACOVA tests with the covariates being pre- and post-manipulation political ideology. If the test statistic (F) is significantly greater than the critical value then we'll conclude a difference.

### Pipeline progress

1. Gather stimuli: **Completed**

2. Create Qualtrics survey: __*In Progress*__

3. Data Collection: Upcoming

4. Analyses: Upcoming


## Results

### Data preparation

Data preparation following the analysis plan.
	
```{r include=T}
### Data Preparation
"Ill be importing data via qualtRics package functionality, and cleaning it here."

#### Load Relevant Libraries and Functions

######Copied from Julies session, dont want to run yet
# install.packages("qualtRics") # comment this out once youve installed
# library(qualtRics)
# library(tidyverse)

#### Import data

#qualtricsData <- fetch_survey(surveyID = "SURVEY ID HERE", force_request = T)

## Save Data to computer
#write_csv(qualtricsData, "./data/qualtricsData.csv")

#### Data exclusion / filtering
"I'll be excluding outliers(?), and people who do not pass the article comprehension check, or the manipulation check."

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

ANCOVAs with experimental condition as the independent variable and demographic characteristics and baseline political ideology as 
covariates.

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Reproduction Attempt

Open the discussion section with a paragraph summarizing the primary result from the key analysis and assess whether you successfully reproduced it, partially reproduced it, or failed to reproduce it.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis of the dataset, (b) assessment of the meaning of the successful or unsuccessful reproducibility attempt - e.g., for a failure to reproduce the original findings, are the differences between original and present analyses ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the reproducibility attempt (if you contacted them).  None of these need to be long.